name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        GCP_URL: ${{ secrets.GCP_URL }}
        GCP_BASE_URL: ${{ secrets.GCP_BASE_URL }}
        S3_URL: ${{ secrets.S3_URL }}
        S3_BASE_URL: ${{ secrets.S3_BASE_URL }}
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
